---
- hosts: sonarqube
  tasks:
      - name: Install package dependencies.
        package:
          name: "{{ item }}"
          state: "present"
        with_items:
          - unzip
  roles:
    - "{{ lookup('env','WORKSPACE') }}/roles/sonarqube.yml"
