---
- hosts: sonarqube
    pre_tasks:
      - name: Install package dependencies.
        package:
          name: "{{ item }}"
          state: "present"
        with_items:
          - unzip
    roles:
    - role: "{{ lookup('env','WORKSPACE') }}/roles/sonarqube.yml"
