- name: add PostgreSQL repo to the repo list
  lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main
    create: yes

- name: Download PostgreSQL software key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install postgresql
  apt:
    pkg:
    - postgresql
    - postgresql-contrib
    state: present

- name: start and enable postgresql
  service:
    name: postgresql
    state: started
    enabled: yes
     

- name: create password for user postgres
  user:
    name: postgres
    group: postgres
    password: postgres

- name: Create a new database sonarqubedb
  postgresql_db:
    name: sonarqube
    state: present
    encoding: UTF-8
  become: true
  become_user: postgres
  
- name: Create user sonarqube
  postgresql_user:
    name: sonar
    password: sonar
    state: present
  become: true
  become_user: postgres
    
- name: Ensure we have access from the new user
  postgresql_privs:
    type: database
    database: sonarqube
    role: sonar
    privs: "ALL"
  become: true
  become_user: postgres

   


   