# [tooling]
# <Tooling-Web-Server-Private-IP-Address>

# [todo]
# <Todo-Web-Server-Private-IP-Address>

[nginx]
172.31.46.186 ansible_ssh_user='ec2_user' ansible_ssh_private_key_file=/home/ec2-user/my_key.pem

# [db:vars]
# ansible_user=ec2-user
# ansible_python_interpreter=/usr/bin/python

[db]
172.31.38.211 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ec2-user/my_key.pem

