# [tooling]
# <Tooling-Web-Server-Private-IP-Address>

# [todo]
# <Todo-Web-Server-Private-IP-Address>

[nginx]
172.31.46.186 ansible_ssh_user='ec2-user' 

[db]
172.31.38.211 ansible_ssh_user='ubuntu' 

