pipeline {
    agent any

  stages {
    stage('SCM Checkout') {
      steps {
         git branch: 'main', url: 'https://github.com/adaanene/ansible-config-mgt.git'
      }
    }
    
    stage('Execute Ansible') {
      steps {
         ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
      }
    }
  }
}
   