pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    }

    stage('Checking') {
      steps {
        script {
          sh 'echo "Checking Stage"'
        }
      }
    }

    stage('Trial') {
      steps {
        script {
          sh 'echo "Trial Stage"'
        }
      }
    }
}   

