---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
   - name: ensure wireshark is at the latest version
     yum:
        name: wireshark
        state: latest

- name: update LB and DB server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: create a folder and a file inside it and set timezone on all servers
  hosts: lb, db, webservers, nfs
  become: yes
  tasks:

    - name: create a folder 
      file:
          path: /home/sample
          state: directory

    - name: create a file
      file:
          path: /home/sample/ansible.txt
          state: touch

    - name: set timezone
      timezone:
          name: Africa/Lagos
