---
- name: nginx assignment
  import_playbook: /home/ec2-user/ansible-config-mgt/static-assignments/nginx.yml


# - hosts: db
# - name: database assignment
#   import_playbook: ../static-assignments/database.yml

